services:
  metatrader:
    image: mt5
    container_name: mt5
    environment:
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    dns:
      - 8.8.8.8
    stdin_open: true
    tty: true
    restart: no